package sblxtract;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ScriptFolderCreator.java
 *
 * Created on Mar 19, 2014, 4:13:17 PM
 */


import java.awt.EventQueue;
import javax.swing.JFileChooser;

/**
 *
 * @author IBM
 */
public class ScriptFolderCreator extends javax.swing.JFrame {

    /** Creates new form ScriptFolderCreator */
    public ScriptFolderCreator() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
       
    
      int result = jFileChooser1.showSaveDialog(this);
      
      if (result == JFileChooser.APPROVE_OPTION) {
    //createFile();
        } 
      else if (result == JFileChooser.CANCEL_OPTION) {
    
                  setVisible(false);
                  jFileChooser1.cancelSelection();
                  jFileChooser1.setVisible(false);
                  
                  EventQueue.invokeLater(new Runnable() {
                  public void run() {
             try {
                     SBLXtractUI sblUI = new SBLXtractUI();
                     sblUI.setVisible(true);

                } catch (Exception e) {
                    System.out.println(e.getMessage());
                }           
    }//GEN-LAST:event_jFileChooser1ActionPerformed
                  });
                          } 
    }    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ScriptFolderCreator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
